import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

function TryOn({ host, config }) {
  const [open,setOpen]=useState(false),[file,setFile]=useState(null),[preview,setPreview]=useState(""),[result,setResult]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false);
  const productTitle=host.dataset.productTitle;
  const selectedImage=()=>{const id=new URL(location.href).searchParams.get("variant")||document.querySelector('form[action*="/cart/add"] [name="id"]')?.value;return config.variants[id]||host.dataset.initialImage};
  useEffect(()=>()=>preview&&URL.revokeObjectURL(preview),[preview]);
  const choose=(photo)=>{if(preview)URL.revokeObjectURL(preview);setFile(photo||null);setPreview(photo?URL.createObjectURL(photo):"");setResult("");setError("")};
  const submit=async(e)=>{e.preventDefault();if(!file||!consent)return;setBusy(true);setError("");setResult("");setStatus("Creating your try-on… This can take up to a minute.");const body=new FormData();body.append("personPhoto",file);body.append("productImageUrl",selectedImage());body.append("productTitle",productTitle);body.append("consent","true");try{const response=await fetch("/apps/virtual-try-on",{method:"POST",body});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Try-on failed.");setResult(data.image);setStatus("Your virtual try-on is ready.")}catch(err){setError(err.message||"Something went wrong.");setStatus("")}finally{setBusy(false)}};
  return <><button className="vto-open" type="button" onClick={()=>setOpen(true)}>{config.buttonLabel}</button>{open&&<div className="vto-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="vto-dialog" role="dialog" aria-modal="true" aria-label={config.modalTitle}><button className="vto-close" type="button" onClick={()=>setOpen(false)} aria-label="Close">×</button><h2>{config.modalTitle}</h2><p>{config.instructions}</p><form onSubmit={submit}><label className="vto-drop"><input type="file" accept="image/jpeg,image/png,image/webp" capture="user" onChange={e=>choose(e.target.files?.[0])} required/><span>{file?file.name:"Choose or take a full-body photo"}</span></label>{preview&&<img className="vto-preview" src={preview} alt="Selected photo preview"/>}<label className="vto-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>{config.consentText}</span></label><button className="vto-generate" disabled={busy} type="submit">{busy?"Generating…":config.generateLabel}</button><div className={error?"vto-status is-error":"vto-status"} role="status" aria-live="polite">{error||status}</div>{result&&<><img className="vto-result" src={result} alt="AI virtual try-on result"/><a className="vto-download" href={result} download="virtual-try-on.jpg">Download result</a></>}</form></section></div>}</>;
}

function mount(){document.querySelectorAll("[data-vto-react-root]").forEach(host=>{if(host.dataset.mounted)return;host.dataset.mounted="true";const config=JSON.parse(host.querySelector("[data-vto-config]").textContent);createRoot(host).render(<TryOn host={host} config={config}/>);});}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",mount):mount();document.addEventListener("shopify:section:load",mount);
