import React, { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

const ACCEPTED_TYPES=["image/jpeg","image/png","image/webp"];
const CART_ID_INPUT='form[action*="/cart/add"] [name="id"]';

function TryOn({ host, config }) {
  // ACCEPTED_TYPES and the 4 MB default mirror api/proxy.js (allowedTypes and MAX_UPLOAD_MB); keep them in step.
  const [open,setOpen]=useState(false),[file,setFile]=useState(null),[result,setResult]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false);
  const productTitle=host.dataset.productTitle||"",variants=config.variants||{},maxMb=Number(config.maxUploadMb)>0?Number(config.maxUploadMb):4;
  const fallbackImage=useMemo(()=>host.dataset.initialImage||Object.values(variants).find(Boolean)||"",[]);
  const resolveImage=()=>{const ids=[new URLSearchParams(location.search).get("variant"),document.querySelector(CART_ID_INPUT)?.value];for(const id of ids)if(id&&variants[String(id)])return variants[String(id)];return fallbackImage};
  const [image,setImage]=useState(resolveImage);
  const preview=useMemo(()=>file?URL.createObjectURL(file):"",[file]);
  const dialogRef=useRef(null),openerRef=useRef(null),tracking=useRef(false);
  // The preview URL is created in the render that displays it and revoked only once React has committed a render that no longer uses it: never revoked while visible, never leaked.
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  // Variant changes while the modal is open: themes update ?variant= and/or the cart form's id input (Dawn dispatches a bubbling change on it). The interval covers themes that only call history.replaceState.
  useEffect(()=>{if(!open)return;const sync=()=>setImage(prev=>{const next=resolveImage();return next&&next!==prev?next:prev});sync();const timer=setInterval(sync,1000);document.addEventListener("change",sync,true);window.addEventListener("popstate",sync);return()=>{clearInterval(timer);document.removeEventListener("change",sync,true);window.removeEventListener("popstate",sync)}},[open]);
  useEffect(()=>{if(!tracking.current){tracking.current=true;return}if(result){setResult("");setStatus("Your selection changed — generate again for the new variant.")}},[image]);
  // Escape to close, initial focus moved into the dialog, focus restored to the trigger on close.
  useEffect(()=>{if(!open)return;const opener=openerRef.current||document.activeElement;dialogRef.current?.focus();const onKeyDown=e=>{if(e.key==="Escape"){e.stopPropagation();setOpen(false)}};document.addEventListener("keydown",onKeyDown,true);return()=>{document.removeEventListener("keydown",onKeyDown,true);if(opener&&document.contains(opener))opener.focus?.()}},[open]);
  const choose=(photo)=>{setResult("");setStatus("");if(!photo){setFile(null);setError("");return true}if(!ACCEPTED_TYPES.includes(photo.type)){setFile(null);setError("That file type is not supported. Choose a JPG, PNG or WebP photo.");return false}if(photo.size>maxMb*1024*1024){setFile(null);setError(`That photo is ${(photo.size/1048576).toFixed(1)} MB. Choose one under ${maxMb} MB.`);return false}setFile(photo);setError("");return true};
  const submit=async(e)=>{e.preventDefault();if(busy||!file||!consent)return;const productImageUrl=resolveImage();if(!productImageUrl){setError("This product has no image to try on.");return}setBusy(true);setError("");setResult("");setStatus("Creating your try-on… This can take up to a minute.");const body=new FormData();body.append("personPhoto",file);body.append("productImageUrl",productImageUrl);body.append("productTitle",productTitle);body.append("consent","true");try{const response=await fetch("/apps/virtual-try-on",{method:"POST",body});const data=await response.json().catch(()=>({}));if(!response.ok||!data.image)throw new Error(data.error||"Try-on failed.");setResult(data.image);setStatus("Your virtual try-on is ready.")}catch(err){setError(err.message||"Something went wrong.");setStatus("")}finally{setBusy(false)}};
  // download is honoured for a data: URL but ignored cross-origin, so an https result is pulled into a blob first, falling back to a new tab if CORS blocks the fetch.
  const save=async(e)=>{if(!result||result.startsWith("data:"))return;e.preventDefault();try{const response=await fetch(result,{mode:"cors"});if(!response.ok)throw new Error("Download failed.");const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download="virtual-try-on.jpg";document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch{window.open(result,"_blank","noopener,noreferrer")}};
  return <><button ref={openerRef} className="vto-open" type="button" onClick={()=>setOpen(true)}>{config.buttonLabel}</button>{open&&<div className="vto-backdrop" role="presentation" onClick={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="vto-dialog" role="dialog" aria-modal="true" aria-label={config.modalTitle} tabIndex={-1} ref={dialogRef}><button className="vto-close" type="button" onClick={()=>setOpen(false)} aria-label="Close">×</button><h2>{config.modalTitle}</h2><p>{config.instructions}</p><form onSubmit={submit}><label className="vto-drop"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{if(!choose(e.target.files?.[0]))e.target.value=""}} required/><span>{file?file.name:"Choose or take a full-body photo"}<span className="vto-hint">JPG, PNG or WebP · up to {maxMb} MB</span></span></label>{preview&&<img className="vto-preview" src={preview} alt="Selected photo preview"/>}<label className="vto-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>{config.consentText}</span></label><button className="vto-generate" disabled={busy} type="submit">{busy?"Generating…":config.generateLabel}</button><div className={error?"vto-status is-error":"vto-status"} role="status" aria-live="polite">{error||status}</div>{result&&<><img className="vto-result" src={result} alt="AI virtual try-on result"/><a className="vto-download" href={result} download="virtual-try-on.jpg" rel="noopener" onClick={save}>Download result</a></>}</form></section></div>}</>;
}

function mount(){document.querySelectorAll("[data-vto-react-root]").forEach(host=>{if(host.dataset.mounted)return;const payload=host.querySelector("[data-vto-config]");if(!payload)return;let config;try{config=JSON.parse(payload.textContent)}catch{return}host.dataset.mounted="true";createRoot(host).render(<TryOn host={host} config={config}/>);});}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",mount):mount();document.addEventListener("shopify:section:load",mount);
