import crypto from "node:crypto";
import fs from "node:fs/promises";
import formidable from "formidable";

export const config = { api: { bodyParser: false } };
const UPSTREAM_MS=90000;
const PRODUCT_IMAGE_MS=15000;
const PRODUCT_IMAGE_MAX=15*1024*1024;
const allowedTypes=new Set(["image/jpeg","image/png","image/webp"]);
const safeMessages={400:"That request could not be processed. Please try again.",413:"That photo is too large. Please upload a smaller one.",415:"Upload a JPG, PNG, or WebP photo.",500:"Try-on failed. Please try again.",502:"The AI service is unavailable right now. Please try again."};
const first=v=>Array.isArray(v)?v[0]:v;
const fail=(status,message)=>Object.assign(new Error(message),{status,safe:true});
const statusFor=e=>{const s=Number(e?.status??e?.httpCode);return Number.isInteger(s)&&s>=400&&s<=599?s:500};
const safeEqual=(a,b)=>{const x=Buffer.from(a||""),y=Buffer.from(b||"");return x.length===y.length&&crypto.timingSafeEqual(x,y)};
function verify(query){const signature=String(query.signature||"");const secret=process.env.SHOPIFY_API_SECRET;if(!signature||!secret)return false;const message=Object.keys(query).filter(k=>k!=="signature").map(k=>`${k}=${Array.isArray(query[k])?query[k].join(","):query[k]}`).sort().join("");return safeEqual(crypto.createHmac("sha256",secret).update(message).digest("hex"),signature)}
function allowedUrl(raw,shop){try{const url=new URL(String(raw).startsWith("//")?`https:${raw}`:raw);const host=url.hostname.toLowerCase();return url.protocol==="https:"&&(host==="cdn.shopify.com"||host.endsWith(".shopifycdn.com")||host===String(shop||"").toLowerCase())}catch{return false}}
async function productImage(raw,shop){if(!allowedUrl(raw,shop))throw fail(400,"The product image URL is not permitted.");const url=String(raw).startsWith("//")?`https:${raw}`:raw;let response;try{response=await fetch(url,{redirect:"error",signal:AbortSignal.timeout(PRODUCT_IMAGE_MS)})}catch(error){console.error("product image fetch failed:",error?.name,error?.message);throw fail(502,"Could not download the product image.")}if(!response.ok){console.error("product image fetch status:",response.status);throw fail(502,"Could not download the product image.")}const type=(response.headers.get("content-type")||"").split(";")[0].trim().toLowerCase();if(!allowedTypes.has(type))throw fail(415,"Unsupported product image format.");if(Number(response.headers.get("content-length")||0)>PRODUCT_IMAGE_MAX)throw fail(413,"Product image is too large.");const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length>PRODUCT_IMAGE_MAX)throw fail(413,"Product image is too large.");return{bytes,type}}
const dataUrl=i=>`data:${i.type};base64,${i.bytes.toString("base64")}`;
// OpenRouter's image endpoint requires only model, prompt and input_references; every other parameter is
// per-endpoint, and GET /api/v1/images/models publishes each model's supported_parameters. Checked
// 2026-09-02: aspect_ratio is offered by every image model in that list, but quality and
// output_compression only by the openai/* ones, and a parameter an endpoint does not accept is rejected
// with a 400 — so those two are gated, which also keeps an unrecognised OPENROUTER_IMAGE_MODEL on the
// minimal, most portable request.
const OPENAI_FAMILY=/^openai\//;
// Vercel caps a function response body at 4.5MB and this base64 string is essentially the whole body.
// output_compression keeps the openai/* models far under it; a model with no compression control can
// return a PNG that does not fit, so fail with a log naming the model instead of a truncated response.
const MAX_RESULT_B64=4200000;
async function generate(person,garment,title){if(!process.env.OPENROUTER_API_KEY){console.error("OPENROUTER_API_KEY is not set");throw fail(500,"AI service is not configured.")}const model=process.env.OPENROUTER_IMAGE_MODEL||"openai/gpt-image-2";const body={model,input_references:[{type:"image_url",image_url:{url:dataUrl(person)}},{type:"image_url",image_url:{url:dataUrl(garment)}}],aspect_ratio:"2:3",prompt:`Create a photorealistic clothing try-on. First image: person. Second image: garment (${String(title||"clothing").slice(0,160)}). Place only that garment on the person and preserve its colors, fabric, pattern, logos and construction. IDENTITY LOCK: keep face, facial features, skin tone, hair, expression, age, hands, body shape, physique, height proportions, pose, camera angle and background unchanged. Never beautify, slim, enlarge, reshape or retouch the person. Add only realistic fit, folds, lighting, shadows and occlusion. Return one finished image.`};if(OPENAI_FAMILY.test(model)){body.quality="medium";body.output_compression=80}let response;try{response=await fetch("https://openrouter.ai/api/v1/images",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,"Content-Type":"application/json","X-Title":"Shopify AI Virtual Try-On"},body:JSON.stringify(body),signal:AbortSignal.timeout(UPSTREAM_MS)})}catch(error){console.error("openrouter request failed:",error?.name,error?.message);throw fail(502,error?.name==="TimeoutError"?"The AI service took too long. Please try again.":"The AI service is unavailable right now. Please try again.")}const json=await response.json().catch(()=>({}));if(!response.ok){console.error("openrouter error:",response.status,json?.error?.type||"",json?.error?.code||"",String(json?.error?.message||"").slice(0,300));const blocked=(response.status===400||response.status===403)&&/moderation|safety|content_policy|policy_violation|flagged/i.test(`${json?.error?.code||""} ${json?.error?.type||""} ${json?.error?.message||""}`);throw fail(blocked?400:502,blocked?"That photo could not be used. Please try a different photo.":"AI generation failed. Please try again.")}const image=json?.data?.[0];if(!image?.b64_json){console.error("openrouter returned no image payload");throw fail(502,"The AI service returned no image. Please try again.")}if(image.b64_json.length>MAX_RESULT_B64){console.error("generated image too large to return:",image.b64_json.length,image.media_type||"",model);throw fail(502,"The generated image was too large. Please try again.")}return`data:${image.media_type||"image/jpeg"};base64,${image.b64_json}`}

export default async function handler(req,res){res.setHeader("Cache-Control","no-store");res.setHeader("Content-Type","application/json; charset=utf-8");if(req.method!=="POST")return res.status(405).json({error:"Method not allowed."});if(!verify(req.query||{})){console.error("rejected app proxy request: invalid signature");return res.status(401).json({error:"Invalid Shopify request."})}const temps=new Set();try{const mb=Number(process.env.MAX_UPLOAD_MB);const max=Math.round((mb>0?mb:4)*1024*1024);let badType=false;const form=formidable({maxFiles:1,maxFileSize:max,filter:part=>{if(part.name!=="personPhoto")return false;if(!allowedTypes.has(part.mimetype)){badType=true;return false}return true}});form.on("fileBegin",(_name,file)=>{if(file?.filepath)temps.add(file.filepath)});const [fields,files]=await form.parse(req);const photo=first(files.personPhoto);if(!photo)throw fail(badType?415:400,badType?"Upload a JPG, PNG, or WebP photo.":"Upload a photo to try this on.");if(first(fields.consent)!=="true")throw fail(400,"Photo-processing consent is required.");const person={bytes:await fs.readFile(photo.filepath),type:photo.mimetype};const garment=await productImage(first(fields.productImageUrl),req.query.shop);const image=await generate(person,garment,first(fields.productTitle));return res.status(200).json({image})}catch(error){const status=statusFor(error);console.error("try-on failed:",status,error?.name,error?.message);return res.status(status).json({error:error?.safe?error.message:safeMessages[status]||safeMessages[500]})}finally{for(const path of temps)await fs.unlink(path).catch(()=>{})}}
