import crypto from "node:crypto";
import fs from "node:fs/promises";
import formidable from "formidable";

export const config = { api: { bodyParser: false } };
const allowedTypes=new Set(["image/jpeg","image/png","image/webp"]);
const first=v=>Array.isArray(v)?v[0]:v;
const safeEqual=(a,b)=>{const x=Buffer.from(a||""),y=Buffer.from(b||"");return x.length===y.length&&crypto.timingSafeEqual(x,y)};
function verify(query){const signature=String(query.signature||"");const secret=process.env.SHOPIFY_API_SECRET;if(!signature||!secret)return false;const message=Object.keys(query).filter(k=>k!=="signature").sort().map(k=>`${k}=${Array.isArray(query[k])?query[k].join(","):query[k]}`).join("");return safeEqual(crypto.createHmac("sha256",secret).update(message).digest("hex"),signature)}
function allowedUrl(raw,shop){try{const url=new URL(String(raw).startsWith("//")?`https:${raw}`:raw);const host=url.hostname.toLowerCase();return url.protocol==="https:"&&(host==="cdn.shopify.com"||host.endsWith(".shopifycdn.com")||host===String(shop||"").toLowerCase())}catch{return false}}
async function productImage(raw,shop){if(!allowedUrl(raw,shop))throw new Error("The product image URL is not permitted.");const url=String(raw).startsWith("//")?`https:${raw}`:raw;const response=await fetch(url,{redirect:"error",signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error("Could not download the product image.");const type=(response.headers.get("content-type")||"").split(";")[0];if(!allowedTypes.has(type))throw new Error("Unsupported product image format.");const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length>15*1024*1024)throw new Error("Product image is too large.");return{bytes,type}}
const ext=t=>t==="image/png"?"png":t==="image/webp"?"webp":"jpg";
async function generate(person,garment,title){if(!process.env.OPENAI_API_KEY)throw new Error("AI service is not configured.");const form=new FormData();form.append("model",process.env.OPENAI_IMAGE_MODEL||"gpt-image-1");form.append("image[]",new Blob([person.bytes],{type:person.type}),`person.${ext(person.type)}`);form.append("image[]",new Blob([garment.bytes],{type:garment.type}),`garment.${ext(garment.type)}`);form.append("size","1024x1536");form.append("quality","medium");form.append("output_format","jpeg");form.append("output_compression","80");form.append("input_fidelity","high");form.append("prompt",`Create a photorealistic clothing try-on. First image: person. Second image: garment (${String(title||"clothing").slice(0,160)}). Place only that garment on the person and preserve its colors, fabric, pattern, logos and construction. IDENTITY LOCK: keep face, facial features, skin tone, hair, expression, age, hands, body shape, physique, height proportions, pose, camera angle and background unchanged. Never beautify, slim, enlarge, reshape or retouch the person. Add only realistic fit, folds, lighting, shadows and occlusion. Return one finished image.`);const response=await fetch("https://api.openai.com/v1/images/edits",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:form,signal:AbortSignal.timeout(115000)});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json?.error?.message||"AI generation failed.");if(json?.data?.[0]?.b64_json)return`data:image/jpeg;base64,${json.data[0].b64_json}`;if(json?.data?.[0]?.url)return json.data[0].url;throw new Error("AI service returned no image.")}

export default async function handler(req,res){res.setHeader("Cache-Control","no-store");if(req.method!=="POST")return res.status(405).json({error:"Method not allowed."});if(!verify(req.query))return res.status(401).json({error:"Invalid Shopify request."});try{const max=Number(process.env.MAX_UPLOAD_MB||4)*1024*1024;const [fields,files]=await formidable({maxFiles:1,maxFileSize:max,filter:part=>part.name==="personPhoto"&&allowedTypes.has(part.mimetype)}).parse(req);const photo=first(files.personPhoto);if(!photo)throw new Error("Upload a JPG, PNG, or WebP photo.");if(first(fields.consent)!=="true")throw new Error("Photo-processing consent is required.");const person={bytes:await fs.readFile(photo.filepath),type:photo.mimetype};const garment=await productImage(first(fields.productImageUrl),req.query.shop);const image=await generate(person,garment,first(fields.productTitle));return res.status(200).json({image})}catch(error){console.error(error.message);return res.status(400).json({error:error.message||"Try-on failed."})}}
